storage: ./.verdaccio
web:
  enable: false
packages:
  "@domovoid/*":
    access: $all
    publish: $anonymous
    unpublish: $anonymous
  "**":
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
